version: "3.9"

services:
  postgres:
    image: postgres:14.1
    networks:
      - springNet
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
  app:
    image: spring-petclinic:2.7.0-SNAPSHOT
    networks:
      - springNet
    ports:
      - "8080:8080"
    environment:
       - "SPRING_PROFILES_ACTIVE=postgres"

networks:
  springNet: